AutomaticTellerMachine/Controllers/CheckingAccountController.cs
using AutomaticTellerMachine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomaticTellerMachine.Controllers
{
    public class CheckingAccountController : Controller
    {
        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var checkingAccount = new CheckingAccount {
                AccountNumber = "0000123456", FirstName = "Michael", LastName = "sullivan", Balance = 500 };
            return View(checkingAccount);
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AutomaticTellerMachine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomaticTellerMachine.Controllers
{
    public class HomeController : Controller
    {
        //[MyLoggingFilter]
        public ActionResult Index()
        {
            return View();
        }

        // Get /home/about
        [ActionName("about-this-atm")]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View("About");
        }

        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Having trouble? Send us a message.";
            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            // TODO : send message to HQ
            ViewBag.TheMessage = "Thanks, we got your message!";
            return View();
        }

        public ActionResult Foo()
        {
            return View("About");
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "ASPNETMVC5ATM1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }
            //return Content(serial);

            //if to show error code
            //return new HttpStatusCodeResult(403);

            //return Json(new { name = "serial", value = serial }, JsonRequestBehavior.AllowGet);

            return RedirectToAction("Index");

            //Check "ActionResult Class" for more return class
        }
    }
}

AutomaticTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutomaticTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<h3>@ViewBag.TheMessage</h3>
<form method="post">
    <textarea name="message"></textarea>
    <input type="submit" value="Send" />

</form>

AutomaticTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-circle-arrow-down"></span>Widthdrawal
        </a>
        <a href="#" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-flash"></span>Quick Cash $100
        </a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-question-sign"></span>Balance Inquiry
        </a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-print"></span>Print Statement
        </a>
        <a href="#" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-transfer"></span>Transfer Funds
        </a>
        <a href="#" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-arrow-up"></span>Deposit
        </a>
    </div>   
</div>

@*<div class="jumbotron">
        <h1>Middle Valley Community Bank</h1>
        <p class="lead">Middle Valley Community Bank offers the first-ever web-based ATM.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Powered by ASP.NET</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Register</h2>
            <p>
                Open an account with us
            </p>
            <p>@Html.ActionLink("Register", "Register", "Account", null, new { @class = "btn btn-default" })</p>
        </div>
        <div class="col-md-4">
            <h2>Log in</h2>
            <p>Access your existing account</p>
            <p>@Html.ActionLink("Log in", "Login", "Account", null, new { @class = "btn btn-default" })</p>
        </div>
    </div>*@
@section scripts {
    <script>var testing = true;</script>}
@*
    You are using @Request.Browser.Browser, and the's OK!  Email us at support@mvcatm.com if you have any problems. Or send us a tweet @@mvcatm.
    @{ var amounts = new List<Decimal> { 100, 25.50m, -40, 275, 99m };}

    <ul>
        @foreach (decimal amount in amounts)
        {
            <li>@formatAmount(amount)</li>
            <text>plain text</text>
            @:plain text
        }
    </ul>

    @helper formatAmount(decimal amount)
    {
        var color = "green";
        if (amount < 0)
        {
            color = "red";
        }
        <span style="color:@color">@String.Format("{0:c}", amount)</span>
    }
*@